### ISSUE TITLE
Make promoted classes recalculate spell slots on promotion

### ISSUE THREAD

**Issue by GamerGoddessDin** [FiendsOfTheElements/FF1Randomizer#460]
Since the random locations for the items necessary to reach bahamut combined with the buffs to XP gain can so greatly increase the chances of being extremely high level before managing to get promotions it would be greatly beneficial if upon promotion your spell slots are recalculated as if you were always that class so that even if you promote at level cap Fighter/Knight and Thief/Ninja can still get their spell slots.

**Comment by wildham0** [comment]
Considering that you have until level 43 to do your class change before your start losing MP with the Knight or the Ninja, I don't think this is much of an issue (maybe if you're doing solo thief with high scaling, but then you're doing solo thief with high scaling).

**Comment by tetron** [comment]
Related to this, there is a new beta flag "Bahamut Cardia dock" map edit which means only the ship, canal and tail are required for promotion instead of being gated on the tail and the floater.  This should make it more likely you will be able to promote earlier in seeds where the floater comes late.
