### ISSUE TITLE
Fetch Quest Rewards are shuffled/loose even when their randomization is turned off

### ISSUE THREAD

**Issue by BrunoCicone** [FiendsOfTheElements/FF1Randomizer#967]
- After turning "Item Shuffle" "Treasures" on, but keeping "Fetch Quest Rewards" off, the Fetch items are still shuffled into the randomization of Incentivized items
- I have experienced this a lot a couple of months back and reported it to the discord, but I've recently come back and the bug still remains: I just got Adamant in the chest to the right of the Crown chest in Marsh Cave B3 (chest that in vanilla has 385 Gil)
- This bug makes it impossible to have randomized treasure and still have vanilla progression of the vanilla map (by that I mean, knowing where to get the essential items to complete the game in vanilla)

**Comment by tukkek** [comment]
I seem to have this problem as well. 0 incentives and 0 incentivized locations, only treasure shuffle on with randomized treasures set to randomized and I get this error every time, even trying new seeds:

> Item placement could not meet incentivization requirements

This seems to obviously be a bug, as I have no inventivization requirements and no key item shuffle at all.

This happens both in stable and beta.

I'd say this is a major bug because this breaks an entire category of use cases for the randomizer. I don't think having key shuffling as a mandatory setting was ever the intention - and if it now is, the user-interface should be updated to reflect it.

**Comment by wildham0** [comment]
Should be fixed in current beta / 4.8.2
