### ISSUE TITLE
Transmooglifier can pass Improved HARM to the modified class that has Wm as its base

### ISSUE THREAD

**Issue by highqualityshaun** [FiendsOfTheElements/FF1Randomizer#999]
report from Sandman#9024 in the development discord

even though the UI grays the option out, if Improved HARM is populated in the flagset, it is being executed for Transmooglifier,
resulting in a Transmooglified class that has HARM all

![image](https://user-images.githubusercontent.com/8323547/233845846-923f4918-3418-4153-93e1-7f6edf60f9a0.png)

**Comment by highqualityshaun** [comment]
Related/similar bug

steel lord blessing can be granted to a transmooglified class which used to be a fighter, but the new class will sometimes be unable to equip it, causing a wasted blessing

**Comment by Tempus** [comment]
White Mage Harm will function properly when the subsequent PR is pulled in, thanks for the report.

Steel Lord Blessing was fixed in a PR on Dec 1st, but was never pulled into beta for some reason. It may also be fixed in the future. Expected behaviour: Cat Claw, Thor, Wood Adept, and Steel Lord will always allow that character to equip the gear regardless of their other permissions.
